baseURL = 'https://hackwimbledon.org/'
languageCode = 'en-uk'
title = 'HackWimbledon'
DefaultContentLanguage = "en"
enableRobotsTXT = true
pagination.pagerSize = 10

[module]
  [[module.imports]]
    path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"



[params]
  background_color_class = "bg-black"
  featured_image = "/img/hwback2.jpg"
  site_logo = "/img/hwlogo2025transp.png"
  show_reading_time = false
  show_word_count = false
  body_classes= "dosis bg-near-white"
  post_content_classes = "dosis"
  recent_posts_number = 3
  mainSections = ["news"]
  custom_css = ["css/custom.css"]

[menu]

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

  [[menu.main]]
  name = "News"
  url = "/news/"
  weight = 2

  [[menu.main]]
  name = "Meetings"
  url = "/meetings/"
  weight = 3

  [[menu.main]]
  name = "People and Projects"
  url = "/peopleandprojects/"
  weight = 4


[params.ananke.social.follow]
new_window_icon = false
networks = [
  "github",
  "mastodon",
  "bluesky",
  "discord"
]

[params.ananke.social.github]
username="makeronicc"

[params.ananke.social.mastodon]
username = "@makeroni"
profilelink = "https://mastodon.org.uk/@makeroni"

[params.ananke.social.bluesky]
username = "hackwimbledon.bsky.social"

[params.ananke.social.networks.discord]
profile = "https://discord.gg/%s"
new_window_icon = false
icon = "discord"

[params.ananke.social.discord]
username = "py5VZarC2u"
